// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIM4.Data.Context;

#nullable disable

namespace PIM4.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PIM4.Models.Entidades.Anexo", b =>
                {
                    b.Property<int>("IdAnexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_anexo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAnexo"));

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_upload");

                    b.Property<int>("IdChamado")
                        .HasColumnType("int")
                        .HasColumnName("id_chamado");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("nome_arquivo");

                    b.HasKey("IdAnexo");

                    b.HasIndex("IdChamado");

                    b.ToTable("Anexo", (string)null);
                });

            modelBuilder.Entity("PIM4.Models.Entidades.Chamado", b =>
                {
                    b.Property<int>("IdChamado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_chamado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdChamado"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_abertura");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("prioridade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("titulo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdChamado");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Chamado", (string)null);
                });

            modelBuilder.Entity("PIM4.Models.Entidades.IASugestao", b =>
                {
                    b.Property<int>("IdSugestao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sugestao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSugestao"));

                    b.Property<string>("CategoriaSugerida")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("categoria_sugerida");

                    b.Property<decimal>("Confiabilidade")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("confiabilidade");

                    b.Property<int>("IdChamado")
                        .HasColumnType("int")
                        .HasColumnName("id_chamado");

                    b.Property<string>("SolucaoSugerida")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("solucao_sugerida");

                    b.HasKey("IdSugestao");

                    b.HasIndex("IdChamado");

                    b.ToTable("IA_Sugestao", (string)null);
                });

            modelBuilder.Entity("PIM4.Models.Entidades.LogAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataAcesso")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Log_Acesso", (string)null);
                });

            modelBuilder.Entity("PIM4.Models.Entidades.Resposta", b =>
                {
                    b.Property<int>("IdResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_resposta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdResposta"));

                    b.Property<DateTime>("DataResposta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_resposta");

                    b.Property<int>("IdChamado")
                        .HasColumnType("int")
                        .HasColumnName("id_chamado");

                    b.Property<int>("IdTecnico")
                        .HasColumnType("int")
                        .HasColumnName("id_tecnico");

                    b.Property<string>("TextoResposta")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("texto_resposta");

                    b.HasKey("IdResposta");

                    b.HasIndex("IdChamado");

                    b.HasIndex("IdTecnico");

                    b.ToTable("Resposta", (string)null);
                });

            modelBuilder.Entity("PIM4.Models.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("PIM4.Models.Entidades.Anexo", b =>
                {
                    b.HasOne("PIM4.Models.Entidades.Chamado", "Chamado")
                        .WithMany()
                        .HasForeignKey("IdChamado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("PIM4.Models.Entidades.Chamado", b =>
                {
                    b.HasOne("PIM4.Models.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PIM4.Models.Entidades.IASugestao", b =>
                {
                    b.HasOne("PIM4.Models.Entidades.Chamado", "Chamado")
                        .WithMany()
                        .HasForeignKey("IdChamado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("PIM4.Models.Entidades.Resposta", b =>
                {
                    b.HasOne("PIM4.Models.Entidades.Chamado", "Chamado")
                        .WithMany()
                        .HasForeignKey("IdChamado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIM4.Models.Entidades.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("IdTecnico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Tecnico");
                });
#pragma warning restore 612, 618
        }
    }
}
